// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhKAgqszoXb1QPadANabZOqGdDu5MlzM',
    appId: '1:777445583671:web:0588f12a371d47e486c8b2',
    messagingSenderId: '777445583671',
    projectId: 'devcare-ef674',
    authDomain: 'devcare-ef674.firebaseapp.com',
    storageBucket: 'devcare-ef674.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwokiL93QxUrascud5jB9mViqNHA-8qUw',
    appId: '1:777445583671:android:3e41522824e9cd3a86c8b2',
    messagingSenderId: '777445583671',
    projectId: 'devcare-ef674',
    storageBucket: 'devcare-ef674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo7tBmHSNowAdAiNVY2PsoXSkSi1rxz00',
    appId: '1:777445583671:ios:684edad48d49a87586c8b2',
    messagingSenderId: '777445583671',
    projectId: 'devcare-ef674',
    storageBucket: 'devcare-ef674.appspot.com',
    iosClientId: '777445583671-f9q3v26if1qkmt02t3c365q4r2do5kqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo7tBmHSNowAdAiNVY2PsoXSkSi1rxz00',
    appId: '1:777445583671:ios:3761bc0caefda0a686c8b2',
    messagingSenderId: '777445583671',
    projectId: 'devcare-ef674',
    storageBucket: 'devcare-ef674.appspot.com',
    iosClientId: '777445583671-sn0eo2dj48oja3t9noli0gp96vgigp6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymast.RunnerTests',
  );
}
